::: {.content-hidden}
$$
{{< include sections/macros.tex >}}
$$
:::


# Revision Guide {.unnumbered}

Revision Guide for the Exam of the module **Numbers Sequences and Series 400297** 2024/25 at the University of Hull. If you have any question or find any typo, please email me at


::: {.content-visible when-format="html"}
<div style="text-align: center;">
**[S.Fanzon@hull.ac.uk](mailto: S.Fanzon@hull.ac.uk)**
</div>
:::


::: {.content-visible when-format="pdf"}
\begin{center}
\textbf{
\href{mailto: S.Fanzon@hull.ac.uk}{S.Fanzon@hull.ac.uk}
}
\end{center}
:::

Full lenght Lecture Notes of the module available at

::: {.content-visible when-format="html"}
<div style="text-align: center;">
**[silviofanzon.com/2024-NSS-Notes](https://www.silviofanzon.com/2024-NSS-Notes)**
</div>
:::


::: {.content-visible when-format="pdf"}
\begin{center}
\textbf{
\href{https://www.silviofanzon.com/2024-NSS-Notes}{silviofanzon.com/2024-NSS-Notes}
}
\end{center}
:::



## Recommended revision strategy {.unnumbered}


Make sure you are very comfortable with:

1. The Definitions, Theorems, Proofs, and Examples contained in this Revision Guide
2. The Tutorial and Homework questions
3. The 2023/24 Exam Paper questions.
4. The Checklist below




## Checklist {.unnumbered}

You should be comfortable with the following topics/taks:


**Preliminaries**

- Prove that $\sqrt{p} \notin \Q$ for $p$ a prime number
- Compute infinite union / intersection
- Show that a binary relation is of equivalence / order / total order
- Characterize the equivalence classes of a given equivalence relation
- Prove statements by induction (such as Bernoulli's inequality)
- Compute the absolute value of a real number
- Understand how to apply triangle inequality



**Real Numbers**

- Determine if a given set with binary operation is a field
- Prove uniqueness of neutral element / inverse
- Computing Sup / Max and Inf / Min of a given set
- Prove that a given set is inductive
- Remember that $\N$, $\Z$ are not fields, $\Q$ is an ordered field, $\R$ is a complete ordered field
- State the axiom of completeness



**Properties of $\R$**

- Know how to use the Archimedean property
- Characterization of sup / inf in terms of $\e$
- Sup / Inf and Max / Min of intervals
- Determine if a given set is finite / countable / uncountable
- Remember that $\N$, $\Z$, $\Q$ are countable
- Remember that $\R$ and the irrationals are uncountable


**Complex Numbers**

- Sum, multiplication, division, conjugate of complex numbers
- Computing the inverse of a complex number
- Find modulus and argument of a complex number
- Compute Cartesian, Trigonometric and Exponential form of a complex number
- Complex exponential and its properties
- Computing powers of complex numbers
- Solving degree 2 polynomial equations in $\C$
- Long division of polynomials
- Solving higher degree polynomial equations in $\C$
- Finding the roots of unity
- Finding the n-th roots of a complex number



**Sequences in $\R$**

- Use the definition of convergence to prove convergence of a given real sequence
- Prove that a given sequence is bounded
- Remember that convergent sequences are bounded
- Use the Algebra of Limits to prove convergence / divergence of a given sequence
- Use the Squeeze Theorem to prove convergence of a given sequence
- Use the Geometric Sequence Test to prove convergence / divergence of a given sequence
- Use the Ratio Test to prove convergence / divergence of a given sequence
- Prove that a sequence is monotone increasing / decreasing
- Know the statement of the Monotone Convergence Theorem
- Memorize the 4 Special Limits, and know how to apply them to study convergence / divergence of a given sequence



**Sequences in $\C$**

- Use the definition of convergence to prove convergence of a given complex sequence
- Prove that a complex sequence is bounded
- Use the Algebra of Limits to prove convergence / divergence of a given sequence
- Use the Geometric Sequence Test / Ratio Test to prove convergence / divergence of a given complex sequence
- Determine convergence of real and imaginary part of a given complex sequence



**Series**

- Compute the partial sums of a given series
- Compute the sum of a telescopic series
- Apply the Necessary Condition for Convergence to prove that a given series is divergent
- Use the Geometric Series test to determine convergence / divergence of a given geometric series
- Compute the sum of a given (convergent) geometric series
- Determine convergence / divergence of non-negative series by using the Cauchy Condensation Test, Comparison Test, Limit Comparison Test and Ratio Test
- Study convergence / divergence of $p$-series
- Prove that a given series converges absolutely
- Prove that a complex series converges / diverges by using the Ratio Test for general series
- Prove that a series converges conditionally
- Use the Dirichlet / Alternate Convergence / Abel's tests to study the convergence of a given series