::: {.content-hidden}
$
{{< include macros.tex >}}
$
:::



# Preliminaries


::: Theorem
The number $\sqrt{2}$ does not belong to $\Q$.
:::


::: Proof

Aassume by contradiction that 
$$
\sqrt{2} \in \Q \,.
$$ {#eq-contradiction-root-2-false}


1. Therefore, there exists $m,n \in \N$, $n \neq 0$, such that 
$$
\frac{m}{n} = \sqrt{2} \,.
$$

2. **Withouth loss of generality**, we can **assume** that $m$ and $n$ have no common factors.

3. Square the equation to get
$$
\frac{m^2}{n^2} = 2 \quad \implies \quad
m^2 = 2 n^2 \,.
$${#eq-contradiction-root-2-3}
Therefore the integer $m^2$ is an even number. 


4. Since $m^2$ is an even number, it follows that also $m$ is an even number. Then there exists $p \in \N$ such that 
$$
m = 2p \,.
$$ {#eq-contradiction-root-2-4}

   
5. Substitute (@eq-contradiction-root-2-4) in (@eq-contradiction-root-2-3) to get
$$
m^2 = 2n^2 \, \implies \,  (2p)^2 = 2n^2 \, \implies \,  4 p^2 = 2 n^2
$$
Dividing both terms by $2$, we obtain
$$
n^2 = 2p^2\,. 
$${#eq-contradiction-root-2-5}

6. We now make a series of observations:
    * Equation (@eq-contradiction-root-2-5) says that $n^2$ is even.
    * The same argument in Step 4 guarantees that also $n$ is even.
    * Therefore $n$ and $m$ are both even, meaning they have $2$ as common factor.
    * But Step 2 says that $n$ and $m$ have no common factors. **Contradiction**

7. Our reasoning has run into a **contradiction**, stemming from assumption (@eq-contradiction-root-2-false). Therefore (@eq-contradiction-root-2-false) is **FALSE**, and so 
$$
\sqrt{2} \notin \Q \,
$$
ending the proof.
:::


## Set Theory


::: Definition
For two sets $A$ and $B$ we define their **union** as the set
$$
A \cup B := \{ x\, \colon \, x \in A  \, \text{ or } \, x \in B \} \,.
$$
The **intersection** of $A$ and $B$ is defined by
$$
A \cap B := \{ x\, \colon \, x \in A  \, \text{ and } \, x \in B \} \,.
$$
We denote the **empty set** by the symbol $\emptyset$. Two sets are **disjoint** if 
$$
A \cap B = \emptyset \,.
$$
Given two sets $A$ and $B$, we say that $A$ is **contained** in $B$, in symbols
$$
A \subseteq B  \,,
$$
if all the elements of $A$ are also contained in $B$. Two sets $A$ and $B$ are **equal**, in symbols
$$
A=B \,,
$$
if they contain the same elements. 
:::


::: Proposition

Let $A$ and $B$ be sets. Then 
$$
A=B \quad \iff \quad A \subseteq B \,\, \text{ and } \,\, B \subseteq A \,.
$$

:::



::: Definition

Let $\Omega$ be a set, and $A_n \subseteq \Omega$ a family of subsets, where $n \in \N$. 

1. The **infinte union** of the $A_n$ is the set
$$
\bigcup_{n \in \N} A_n := \{ x \in \Omega \, \colon \, x \in A_n \,\, \text{ for at least one } \,\, n \in \N \} \,.
$$

2. The **infinte intersection** of the $A_n$ is the set 
$$
\bigcap_{n \in \N} A_n := \{ x \in \Omega \, \colon \, x \in A_n \,\, \text{ for all } \,\, n \in \N \} \,.
$$

:::


::: Example 

**Question.**
Define $\Omega:=\N$ and a family $A_n$ by
$$
A_n = \{ n, n+1, n+2, n+3,  \ldots \} \,, \quad n \in \N \,.
$$

1. Prove that
$$
\bigcup_{n \in \N} A_n = \N \,.
$$ {#eq-infinite-union}

2. Prove that 
$$
\bigcap_{n \in \N} A_n = \emptyset \,.
$$ {#eq-infinite-intersection}

**Solution.**

1. Assume that $m \in \cup_n A_n$. Then $m \in A_n$ for at least one $n \in \N$. Since $A_n \subseteq \N$, we conclude that $m \in \N$. This shows 
$$
\bigcup_{n \in \N} A_n \subseteq \N \,.
$$
Conversely, suppose that $m \in \N$. By definition $m \in A_m$. Hence there exists at least one index $n$, $n=m$ in this case, such that $m \in A_n$. Then by definition $m \in \cup_{n \in \N} A_n$, showing that
$$
\N \subseteq \bigcup_{n \in \N} A_n \,.
$$
This proves (@eq-infinite-union).

2. Suppose that (@eq-infinite-intersection) is false, i.e., 
$$
\bigcap_{n \in \N} A_n \neq \emptyset \,.
$$
This means there exists some $m \in \N$ such that $m \in \cap_{n \in \N} A_n$. Hence, by definition, $m \in A_n$ for all $n \in \N$. However $m \notin A_{m+1}$, yielding a contradiction. Thus (@eq-infinite-intersection) holds.
:::



::: Definition
Let $A,B \subseteq \Omega$. The **complement** of $A$ with respect to $B$ is the set of elements of $B$ which do not belong to $A$, that is
$$
B \smallsetminus A := \{ x \in \Omega \, \colon \, x \in B \, \text{ and } \, x \notin A \} \,.
$$
In particular, the complement of $A$ with respect to $\Omega$ is denoted by 
$$
A^c := \Omega \smallsetminus A := \{ x \in \Omega \, \colon \, x \notin A \} \,.
$$
:::


::: Example

**Question.** Suppose $A, B \subseteq \Omega$. Prove that
$$
A \subseteq B  \iff B^c \subseteq A^c \,.
$$

**Solution.** Let us prove the above claim:

- First implication $\implies$:  
Suppose that $A \subseteq B$. We need to show that $B^c \subseteq A^c$. Hence, assume $x \in B^c$. By definition this means that $x \notin B$. Now notice that we cannot have that $x \in A$. Indeed, assume $x \in A$.  By assumption we have $A \subseteq B$, hence $x \in B$. But we had assumed $x \in B$, contradiction. Therefore it must be that $x \notin A$. Thus $B^c \subseteq A^c$.

- Second implication $\impliedby$:  Note that, for any set, 
$$
(A^c)^c = A \,.
$$
Hence, by the first implication,
$$
B^c \subseteq A^c \, \implies \, (A^c)^c \subseteq (B^c)^c \, \implies \, A \subseteq B \,.
$$
:::



::: Proposition
## De Morgan's Laws

Suppose $A,B \subseteq \Omega$. Then
$$
(A \cap B)^c = A^c \cup B^c  \,, \qquad 
(A \cup B)^c = A^c \cap B^c  \,.
$$ 

:::



::: Definition
Let $\Omega$ be a set. The **power set** of $\Omega$ is
$$
\mathcal{P}(\Omega) := \{ A \divider A \subseteq \Omega \}\,.
$$
:::

::: Example

**Question.** Compute the power set of
$$
\Omega = \{ x, y, z \}\,.
$$

**Solution.** $\mathcal{P}(\Omega)$ has $2^3 = 8$, and
\begin{align}
\mathcal{P}(\Omega) = \{ \emptyset, & \, \{x\} , \,  \{y\} , \, \{z\} , \{x,y\} \\
&  \{x,z\}, \, \{y,z\} , \, \{x,y,z\} \} \,. 
\end{align}
:::



::: Definition

Let $A,B$ be sets. The **product** of $A$ and $B$ is the set of pairs
$$
A \times B := \{ (a,b) \, \colon \, a \in A, \, b \in B \} \,.
$$

:::



## Relations

::: Definition

Suppose $A$ is a set. A **binary relation** $R$ on $A$ is a subset 
$$
R \subseteq A \times A \,.
$$

:::

::: Definition
### Equivalence relation

A binary relation $R$ is called an **equivalence relation** if it satisfies the following properties:

1. **Reflexive**: For each $x \in A$ one has 
$$
(x,x) \in R \,, 
$$

2. **Symmetric**: We have
$$
(x,y) \in R \implies (y,x) \in R
$$


3. **Transitive**: We have
$$
(x,y) \in R \,, \,\, (y,z) \in R  \implies (x,z) \in R 
$$


If $(x,y) \in R$ we write
$$
x \sim y 
$$
and we say that $x$ and $y$ are **equivalent**.

:::



::: Definition
### Equivalence classes

Suppose $R$ is an **equivalence relation** on $A$. The **equivalence class** of an element $x \in A$ is the set
$$
[x]:=\{ y \in A \, \colon \, y \sim x \} \,.
$$
The set of equivalence classes of elements of $A$ with respect to the equivalence relation $R$ is denoted by 
$$
A / R \, := A / \!\sim \, :=  \,\{ [x] \, \colon \, x \in A \} \,.
$$


:::




::: Proposition

Let $\sim$ be an equivalence relation on $A$. Then

1. For each $x \in A$ we have
$$
[x] \neq \emptyset
$$

2. For all $x,y \in A$ it holds
$$
x \sim y \quad \iff \quad  [x] = [y] \,.
$$

:::




::: Example
### Equality is an equivalence relation

**Question.** The equality defines a **binary relation** on $\Q \times \Q$, via
$$
R:=\{ (x,y) \in \Q \times \Q \, \colon \, x=y  \} \,.
$$

1. Prove that $R$ is an **equivalence relation**.
2. Prove that $[x] = \{x\}$ and compute $\Q / R$.

**Solution.** 

1. We need to check that $R$ satisfies the 3 properties of an equivalence relation:

    - Reflexive: It holds, since $x=x$ for all $x \in \Q$,

    - Symmetric: Again $x = y$ if and only if $y = x$,

    - Transitive: If $x = y$ and $y = z$ then $x = z$.

    Therefore, $R$ is an equivalence relation.

2. The class of equivalence of $x \in \Q$ is given by
$$
[x] = \{ x \}\,,
$$
that is, this relation is quite trivial, given that each element of $\Q$ can only be related to itself. The quotient space is then 
$$
\Q / R = \{ [x] \divider x \in \Q \} = \{  \{ x\} \divider x \in \Q \}  \,.
$$

:::



::: Example

**Question.** Let $R$ be the binary relation on the set $\Q$ of rational numbers defined by
$$
x \sim y  \iff x-y \in \Z \,.
$$

1. Prove that $R$ is an equivalence relation on $\Q$.
2. Compute $[x]$ for each $x \in \Q$.
3. Compute $\Q/R$.


**Solution.**

1. We have:

    - Reflexive: Let $x \in \Q$. Then $x-x = 0$ and $0 \in \Z$. Thus $x \sim x$.

    - Symmetric: If $x \sim y$ then $x-y \in \Z$. But then also  
    $$
    -(x-y) = y - x \in \Z
    $$
    and so $y \sim x$.

    - Transitive: Suppose $x \sim y$ and $y \sim z$. Then 
    $$
    x - y \in \Z \,  \text{ and } \, y - z \in \Z \,.
    $$
    Thus, we have
    $$
    x-z = (x-y) + (y-z) \in \Z
    $$
    showing that $x \sim z$. 

    Thus, we have shown that $R$ is an equivalence relation on $\Q$.

2. Note that
$$
x \sim y \quad \iff \quad \exists \, n \in \Z \, \text{ s.t. } \, y = x + n \,.
$$
Therefore the equivalence classes with respect to $\sim$ are
$$
 [x] = \{  x + n \ \colon \ n \in \Z  \}  \,.
$$
Each equivalence class has exactly one element in $[0,1) \cap \Q$, meaning that:
$$
\forall x \in \Q \,, \,\, \exists! \, q \in \Q \st  0 \leq q < 1 \, \text{ and } \, q \in [x]\,.
$${#eq-equivalence-rel}
Indeed: take $x \in \Q$ arbitrary. Then $x \in [n,n+1)$ for some 
$n \in \Z$. Setting $q:=x-n$ we obtain that
$$
x = q + n \,, \qquad q \in [0,1) \,,
$$
proving (@eq-equivalence-rel). In particular (@eq-equivalence-rel) implies that for each $x \in \Q$ there exists $q \in [0,1) \cap \Q$ such that
$$
[x] = [q] \,.
$$

3. From Point 2 we conclude that
$$
\Q / R = \{ [x] \divider x \in \Q \} = \{ q \in \Q \divider 0 \leq q <1  \} \,.
$$
:::




::: Definition
### Partial order

A binary relation $R$ on $A$ is called a **partial order** if it satisfies the following properties:

1. **Reflexive**: For each $x \in A$ one has 
$$
(x,x) \in R \,, 
$$

2. **Antisymmetric**: We have
$$
(x,y) \in R \,  \text{ and } \, (y,x) \in R \implies x = y 
$$


3. **Transitive**: We have
$$
(x,y) \in R \,, \,\, (y,z) \in R  \implies (x,z) \in R 
$$
:::




:::  Definition
### Total order

A binary relation $R$ on $A$ is called a **total order relation** if it satisfies the following properties:

1. **Partial order**: $R$ is a partial order on $A$.
2. **Total**: For each $x,y \in A$ we have
$$
(x, y) \in R \,\, \mbox{ or } \,\, (y,x) \in R \,.
$$

:::




::: Example
### Set inclusion is a partial order but not total order

**Question.** Let $\Omega$ be a non-empty set and consider its **power set**
$$
\mathcal{P}(\Omega) = \{ A \divider A \subseteq \Omega  \}\,.
$$
The inclusion defines **binary relation** on $\mathcal{P}(\Omega) \times \mathcal{P}(\Omega)$, via
$$
R:=\{ (A,B) \in \mathcal{P}(\Omega) \times \mathcal{P}(\Omega) \, \colon \, A \subseteq B  \} \,.
$$

1. Prove that $R$ is an **order relation**.
2. Prove that $R$ is **not a total order**.

**Solution.**

1. Check that $R$ is a partial order relation on $\mathcal{P}(\Omega)$:
    - Reflexive: It holds, since $A \subseteq A$ for all $A \in \mathcal{P}(\Omega)$.
    - Antisymmetric: If $A \subseteq B$ and $B \subseteq A$, then $A=B$.
    - Transitive: If $A \subseteq B$ and $B \subseteq C$, then, by definition of inclusion, $A \subseteq C$.

2. In general, $R$ is **not** a total order. For example consider
$$
\Omega = \{x, y\}\,.
$$
Thus
$$
\mathcal{P}(\Omega)  = \{ \emptyset , \, \{x\} , \, \{y\} , \, \{x,y\} \}\,.
$$
If we pick $A=\{x\}$ and $B=\{y\}$ then $A \cap B = \emptyset$, meaning that 
$$
A \not\subseteq B \,, \quad  B \not\subseteq A \,.
$$
This shows $R$ is not a total order.
:::




::: Example
### Inequality is a total order

**Question.** Consider the binary relation
$$
R:=\{ (x,y) \in \Q \times \Q \, \colon \, x \leq y  \} \,.
$$
Prove that $R$ is a **total order relation**.

**Solution.** We need to check that:

1. Reflexive: It holds, since $x \leq x$ for all $x \in \Q$,

2. Antisymmetric: If $x \leq y$ and $y \leq x$  then $x = y$.

3. Transitive: If $x \leq y$ and $y \leq z$ then $x \leq z$.

Finally, we halso have that $R$ is a **total order** on $\Q$, since for all $x,y \in \Q$ we have
$$
x \leq y \,\, \text{ or } \,\, y \leq x \,.
$$
:::




## Induction



::: Definition
### Principle of Inducion

Let $\alpha(n)$ be a statement which depends on $n \in \N$. Suppose that 

1. $\alpha(1)$ is true, and
2. Whenever $\alpha(n)$ is true, then $\alpha(n+1)$ is true.

Then $\alpha(n)$ is true for all $n \in \N$.
:::


::: Example 
### Formula for summing first $n$ natural numbers

**Question.** Prove by induction that the following formula holds for all $n \in \N$:
$$
1 + 2 + 3 + \ldots + (n-1) + n = \frac{n(n+1)}{2} \,.
$$ {#eq-formula-sum-naturals}


**Solution**. Define
$$
S(n) = 1 + 2 + \ldots + n \,.
$$
This way the formula at (@eq-formula-sum-naturals) is equivalent to
$$
S(n) = \frac{n(n+1)}{2} \,, \quad \forall \, n \in \N \,.
$$

1. It is immediate to check that (@eq-formula-sum-naturals) holds for $n=1$.
2. Suppose (@eq-formula-sum-naturals) holds for $n = k$. Then
\begin{align}
S(k+1) & = 1 + \ldots +  k + (k+1) \\
       & = S(k) + (k+1) \\
       & = \frac{k(k+1)}{2}  + (k+1) \\
& = \frac{ k(k+1) + 2(k+1) }{2} \\
& = \frac{(k+1)(k+2)}{2}
\end{align}
where in the first equality we used that (@eq-formula-sum-naturals) holds for $n=k$. We have proven that
$$
S(k+1) = \frac{(k+1)(k+2)}{2}\,.
$$
The RHS in the above expression is exactly the RHS of  (@eq-formula-sum-naturals) computed at $n = k+1$. Therefore, we have shown that formula (@eq-formula-sum-naturals) holds for $n = k+1$.

By the Principle of Induction, we conclude that (@eq-formula-sum-naturals) holds for all $n \in \N$.

:::


::: Example
### Bernoulli's inequality

**Question.** Let $x \in \R$ with $x>-1$. Bernoulli's inequality states that
$$
(1+x)^{n} \geq 1+n x \,, \quad \forall \, n \in \N \,.
$${#eq-bernoulli-inequality}
Prove Bernoulli's inequality by induction.


**Solution.** Let $x \in \mathbb{R}, x>-1$. We prove the statement by induction:

- Base case: (@eq-bernoulli-inequality) holds with equality when $n=1$.

- Induction hypothesis: Let $k \in \N$ and suppose that (@eq-bernoulli-inequality) holds for $n=k$, i.e.,
$$
(1+x)^{k} \geq 1+k x \,.
$$
Then
\begin{align*}
(1+x)^{k+1} & = (1+x)^{k}(1+x) \\
            & \geq(1+k x)(1+x) \\
            & =1+k x+x+k x^{2} \\
            & \geq 1+(k+1) x \,,
\end{align*}
where we used that $kx^2 \geq 0$. Then (@eq-bernoulli-inequality) holds for $n=k+1$.

By induction we conclude (@eq-bernoulli-inequality).

:::





## Absolute value

::: Definition
### Absolute value 
For $x \in \R$ we define its **absolute value** as the quantity
$$
|x| = 
\begin{cases}
x  & \text{ if } \, x \geq 0 \\
-x  & \text{ if } \, x < 0 
\end{cases}
$$
:::

::: Proposition
For all $x \in \R$ they hold:

1. $|x| \geq 0$.
2. $|x| = 0$ if and only if $x = 0$.
3. $|x| = |-x|$.

:::


::: {.Lemma #lemma-absolute-value}
Let $x,y \in \R$. Then
$$
|x| \leq y  \iff -y \leq x \leq y \,.
$$
:::

::: Corollary
Let $x,y \in \R$. Then
$$
|x| < y  \iff -y < x < y \,.
$$
:::




::: Theorem
### Triangle inequality  {#theorem-triangle-inequality}

For every $x, y \in \R$ we have
$$
| |x| - |y| | \leq |x+y| \leq |x| + |y| \,.
$$ {#eq-triangle-inequality}
:::




::: Proposition
For any $x,y \in \R$ it holds
$$
||x|-|y|| \leq |x-y| \leq |x|+|y|\,.
$${#eq-triangle-inequality-bis}
Moreover for any  $x,y,z \in \R$ it holds
$$
|x-y| \leq |x-z| + |z-y| \,.
$$
:::
