::: {.content-hidden}
$
{{< include macros.tex >}}
$
:::




# Sequences in $\mathbb{C}$



::: Definition 
### Convergent sequence in $\mathbb{C}$ {#definition-convergent-sequence-C}

We say that a sequence $\left(a_{n}\right)$ in $\mathbb{C}$ **converges** to $a \in \mathbb{C}$, or equivalently has limit $a$, denoted by
$$
\lim_{n \rightarrow \infty} a_{n}=a  \quad \mbox{ or } \quad a_n \to a \,,
$$
if it holds:
$$
\forall \, \varepsilon>0 , \, \exists \, N \in \mathbb{N} \, \mbox{ s.t. } \, \forall \, n \geq N \,, \,\left|a_{n}-a\right| < \varepsilon \,.
$$

If there exists $a \in \mathbb{C}$ such that $\lim _{n \rightarrow \infty} a_{n}=a$, we say that the sequence $\left(a_{n}\right)$ is **convergent**.

:::



::: Example 

**Question.** Using Definition \ref{definition-convergent-sequence-C}, prove that
$$
\lim_{n \rightarrow \infty} \frac{(3+i) n-7 i}{n}=3+i \,.
$$

**Solution.**

*Part 1. Rough Work.* Let $\varepsilon >0$. We need to clarify for which values of $n$ the following holds: 
$$
\left|\frac{(3+i) n-7 i}{n}-(3+i)\right| < \varepsilon \,.
$$
We have
$$
\left|\frac{(3+i) n-7 i}{n}-(3+i)\right| 
 = \frac{|-7 i|}{n} 
 = \frac{7}{n} \,.\\
$$
Therefore 
$$
 \frac{7}{n} < \varepsilon \quad \iff \quad n > \frac{7}{\varepsilon} \,.
$$

*Part 2. Formal Proof.*
We want to prove that for all $\varepsilon>0$ there exists $N \in \mathbb{N}$ such that
$$
\left|\frac{(3+i) n-7 i}{n}-(3+i)\right| < \varepsilon \,, \qquad \forall \, n \geq N \,.
$$
Let $\varepsilon>0$. Choose $N \in \mathbb{N}$ such that
$$
N > \frac{7}{\varepsilon} \,.
$$
The above is equivalent to
$$
\frac{7}{N} < \varepsilon \,.
$$
For $n \geq N$ we have
$$
\left|\frac{(3+i) n-7 i}{n}-(3+i)\right| = \frac{7}{n} \leq \frac{7}{N}  < \varepsilon \,. 
$$

:::


::: Definition 
### Bounded sequence in $\mathbb{C}$

A sequence $\left(a_{n}\right)$ in $\mathbb{C}$ is called **bounded** if there exists a constant $M \in \mathbb{R}$, with $M>0$, such that
$$
\left|a_{n}\right| \leq M \,, \quad \forall \, n \in \mathbb{N} \,.
$$

:::



::: {.Theorem  #theorem-convergent-bounded-C}

If a sequence $\left(a_{n}\right)$ in $\mathbb{C}$ converges, then the sequence is bounded.

:::



::: Definition
### Divergent sequences in $\mathbb{C}$

We say that a sequence $\left(a_{n}\right)$ in $\mathbb{C}$ is **divergent** if it is not convergent.

:::



::: Corollary

Let $\left(a_{n}\right)$ be a complex sequence. If $\left(a_{n}\right)$ is not bounded, then it is divergent.

:::






## Algebra of limits in $\mathbb{C}$



::: Theorem 
### Algebra of limits in $\mathbb{C}$ {#theorem-algebra-limits-C} 

Let $\left(a_{n}\right)$ and $\left(b_{n}\right)$ be sequences in $\mathbb{C}$. Suppose that
$$
\lim_{n \rightarrow \infty} a_{n}=a \,, \quad  \lim_{n \rightarrow \infty} b_{n}=b \,,
$$
for some $a,b \in \mathbb{C}$. Then,

1. Limit of sum is the sum of limits:
$$
\lim_{n \rightarrow \infty}\left(a_{n} \pm b_{n}\right)=a \pm b
$$

2. Limit of product is the product of limits: 
$$
\lim _{n \rightarrow \infty}\left(a_{n}  b_{n}\right) = a  b 
$$

3. If $b_{n} \neq 0$ for all $n \in \mathbb{N}$ and $b \neq 0$, then 
$$
\lim_{n \rightarrow \infty} \left(\frac{a_{n}}{b_{n}}\right)=\frac{a}{b} 
$$

:::




::: Example 

**Question.** Compute the limit of
$$
a_{n} = \frac{(2-i) n^{2}+6 i n-5-3 i}{(6+3 i) n^{2}+11 i} \,.
$$

**Solution.** Factor $n^2$, the largest power of $n$ in the denominator,
$$
a_{n}= 
\frac{(2-i)+\dfrac{6 i}{n}- \dfrac{5}{n^2}- \dfrac{3 i}{ n^{2}} }{(6+3 i)+\dfrac{11 i}{n^{2}}} \longrightarrow \frac{2-i}{6+3 i} \,,
$$
where we used the Algebra of Limits. Finally,
$$
\frac{2-i}{6+3 i} 
 =\frac{(2-i)(6-3 i)}{(6+3 i)(6-3 i)}
 =\frac{1}{5}-\frac{4}{15} i \,.
$$

:::



## Convergence to zero




::: {.Theorem #theorem-convergence-zero-C}

Let $\left(a_{n}\right)$ be a sequence in $\mathbb{C}$ and suppose that 
$$
\lim_{n \rightarrow \infty}\left|a_{n}\right|=0 \,.
$$
Then 
$$
\lim_{n \rightarrow \infty} a_{n}=0 \,.
$$

:::



::: Example 

**Question.** Prove that $a_n \to 0$, where
$$
a_{n}=\left(\frac{1}{2}+\frac{1}{3} i\right)^{n} \,.
$$

**Solution.** We have
\begin{align*}
\left|a_{n}\right| & = \left|\left(\frac{1}{2}+\frac{1}{3} i\right)^{n}\right| \\
& = \left|\frac{1}{2}+\frac{1}{3} i\right|^{n} \\
& = \left(\sqrt{\left(\frac{1}{2}\right)^{2}+\left(\frac{1}{3}\right)^{2}}\right)^{n} \\
& = \left(\sqrt{\frac{13}{36}}\right)^{n} \,.
\end{align*}
Since
$$
\left|\sqrt{\frac{13}{36}} \right| < 1 \,,
$$ 
by the Geometric Sequence Test for real sequences, we conclude that
$$
\left|a_{n}\right| \rightarrow 0 \,.
$$
Hence $a_n \to 0$ by Theorem \ref{theorem-convergence-zero-C}.

:::




::: Example

**Question.** Consider the sequence
$$
a_{n}:=\frac{2 i \cos (3 n) n+(7-i) n^{2}}{3 n^{2}+2 i n+\sin (2 n)} \,.
$$
Prove that 
$$
\lim_{n \to \infty} a_n  = \frac{7}{3}-\frac{1}{3} i \,.
$$

**Solution.** We divide by the largest power in the denominator, to get
$$
a_{n} = \frac{\dfrac{2 i \cos (3 n)}{ n} + (7-i) }{3+ \dfrac{2 i}{n} + \dfrac{\sin (2 n)}{n^{2}}} \,.
$$
Notice that
$$
- 1 \leq \cos (3 n) \leq 1 \,, \quad \forall \, n \in \mathbb{N} \,,
$$
and thus
$$
- \frac{2}{n} \leq \frac{2 \cos (3 n)}{n} \leq \frac{2}{n} \,, \quad \forall \, n \in \mathbb{N} \,.
$$
Since 
$$
-\frac{2}{n} \longrightarrow 0 \,, \quad 
\frac{2}{n} \longrightarrow 0 \,,
$$
by the Squeeze Theorem we conclude that also
$$
\frac{2 \cos (3 n)}{n} \to 0 \,.
$$
In particular we have shown that
$$
\left| \dfrac{2 i \cos (3 n)}{ n} \right| =
\left| \dfrac{2 \cos (3 n)}{ n} \right| \to 0 \,.
$$
Using Theorem \ref{theorem-convergence-zero-C} we infer
$$
\dfrac{2 i \cos (3 n)}{ n} \to 0 \,.
$$
Similarly, 
$$
- \frac{1}{n^{2}} \leq \frac{\sin (2 n)}{n^{2}} \leq - \frac{1}{n^{2}} \,, \quad \forall \, n \in \mathbb{N} \,.
$$
Since 
$$
- \frac{1}{n^{2}} \longrightarrow 0 \,, \quad
\frac{1}{n^{2}} \longrightarrow 0  \,,
$$
by the Squeeze Theorem we conclude
$$
\frac{\sin (2 n)}{n^2}  \longrightarrow 0 \,.
$$
Finally, we have
$$
\left|  \frac{2i}{n}  \right| = \frac{2}{n} \longrightarrow 0 \,,
$$
and therefore 
$$
\frac{2i}{n} \longrightarrow 0 
$$
by Theorem \ref{theorem-convergence-zero-C}. Using the Algebra of Limits in 
$\mathbb{C}$ we conclude
$$
a_{n} = \frac{\dfrac{2 i \cos (3 n)}{ n} + (7-i) }{3+ \dfrac{2 i}{n} + \dfrac{\sin (2 n)}{n^{2}}}
\longrightarrow \frac{ 0+ (7-i) }{3+0+0}=\frac{7}{3}-\frac{1}{3} i \,.
$$

:::




## Geometric sequence Test and Ratio Test in $\mathbb{C}$




::: Theorem 
### Geometric sequence Test in $\mathbb{C}$ 

Let $x \in \mathbb{C}$ and let $\left(a_{n}\right)_{n \in \mathbb{N}}$ be the geometric sequence in $\mathbb{C}$ defined by
$$
a_{n}:=x^{n} \,.
$$
We have:

1. If $|x|<1$, then 
$$
\lim_{n \to \infty} a_{n} = 0 \,.
$$

2. If $|x|>1$, then sequence $\left(a_{n}\right)$ is unbounded, and hence divergent.

:::



::: Example 

**Question.** Prove that $a_n \to 0$, where
$$
a_{n}=\frac{(-1+4 i)^{n}}{(7+3 i)^{n}} \,.
$$

**Solution.** We first rewrite
$$
a_{n}=\frac{(-1+4 i)^{n}}{(7+3 i)^{n}}=\left(\frac{-1+4 i}{7+3 i}\right)^{n}
$$
Then, we compute
\begin{align*}
\left|\frac{-1+4 i}{7+3 i}\right| & =\frac{|-1+4 i|}{|7+3 i|} \\
& = \frac{\sqrt{(-1)^{2}+4^{2}}}{\sqrt{7^{2}+3^{2}}} \\
& = \frac{\sqrt{17}}{\sqrt{58}} \\
& = \sqrt{\frac{17}{58}} \\
& < 1 \,
\end{align*}
By the Geometric Sequence Test $a_{n} \rightarrow 0$.

:::

::: Example

**Question.** Prove that $a_n$ diverges, where
$$
a_{n}=\frac{(-5+12 i)^{n}}{(3-4 i)^{n}} \,.
$$


**Solution.** We first rewrite
$$
a_{n}=\frac{(-5+12 i)^{n}}{(3-4 i)^{n}}=\left(\frac{-5+12 i}{3-4 i}\right)^{n} \,.
$$
We compute
\begin{align*}
\left|\frac{-5+12 i}{3-4 i}\right| & = \frac{|-5+12 i|}{|3-4 i|} \\
& = \frac{\sqrt{5^{2}+(-12)^{2}}}{\sqrt{3^{2}+(-4)^{2}}} \\
& = \frac{13}{5} \\
& > 1 \,.
\end{align*}
By the Geometric Sequence Test, the sequence $a_n$ diverges.

:::

::: Example

**Question.** Prove that $a_n$ diverges, where
$$
a_{n}= \exp \left( \frac{i \pi}{2} n \right)\,.
$$

**Solution.** We have
$$
\left|a_{n}\right|=\left|e^{\frac{i \pi}{2} n}\right|=1 \,,
$$
and hence the Geometric Sequence Test cannot be applied. However, we can see that 
$$
a_n = (i,-1,-i, 1, i,-1,-i, 1, \ldots ) \,,
$$
that is, $a_n$ assumes only the values $\{i,-1,-i,1\}$, and each of them
is assumed infinitely many times. Therefore $a_n$ is oscillating, and thus divergent.


:::



::: Theorem 
### Ratio Test in $\mathbb{C}$ {#theorem-ratop-test-C}

Let $\left(a_{n}\right)$ be a sequence in $\mathbb{C}$ such that
$$
a_{n} \neq 0 \,, \quad \forall \, n \in \mathbb{N} \,.
$$ 


1. Suppose that the following limit exists:
$$
L:=\lim_{n \to \infty}\left|\frac{a_{n+1}}{a_{n}}\right| \,.
$$
Then,

    - If $L<1$ we have
    $$
    \lim_{n \to\infty} a_{n}=0 \,.
    $$

    - If $L>1$, the sequence $\left(a_{n}\right)$ is unbounded, and hence does not converge.

2. Suppose that there exists $N \in N$ and $L>1$ such that
$$
\left|\frac{a_{n+1}}{a_{n}}\right| \geq L \,, \quad \forall \, n \geq N \,. 
$$
Then the sequence $a_n$ is unbounded, and hence does not converge.

:::


::: Example 

**Question.** Study the convergence / divergence of the sequence
$$
a_{n}=\frac{(4-3 i)^{n}}{(2 n) !} \,.
$$

**Solution.** We compute
\begin{align*}
\left|\frac{a_{n+1}}{a_{n}}\right| & =\left|\frac{(4-3 i)^{n+1}}{(2(n+1)) !}  \frac{(2 n) !}{(4-3 i)^{n}}\right| \\
& = \frac{|4-3 i|^{n+1}}{|4-3 i|^{n}} \cdot \frac{(2 n) !}{(2 n+2) !} \\
& = \frac{|4 - 3i|}{(2 n+2)(2 n+1)} \\
& =\frac{\sqrt{4^{2}+(-3)^{2}}}{(2 n+2)(2 n+1)} \\
& = \frac{5}{(2 n+2)(2 n+1)} \\
& = \frac{ \dfrac{5}{n^{2}}}{ \left(2+ \dfrac{2}{n} \right) \left(2+ \dfrac{1}{n} \right) } \longrightarrow L = 0 \,.
\end{align*}
Since $L=0 < 1$, by the Ratio Test in $\mathbb{C}$ we infer $a_{n} \to 0$. 

:::




## Convergence of real and imaginary part


::: {.Theorem  #theorem-convergence-real-imaginary}

Let $\left(z_{n}\right)_{n \in \mathbb{N}}$ be a sequence in $\mathbb{C}$. For $n \in \mathbb{N}$, let $a_{n}, b_{n} \in \mathbb{R}$ such that 
$$
z_{n}=a_{n}+b_{n} i \,.
$$
Let $z=a+b i$, 
with $a, b \in \mathbb{R}$. Then
$$
\lim_{n \rightarrow \infty} z_{n}=z \quad \iff \quad \lim_{n \rightarrow \infty} a_{n}=a \,, \quad \lim_{n \rightarrow \infty} b_{n}=b \text {. }
$$

:::



::: Example 

**Question.** Consider the complex sequence
$$
z_{n}:=\frac{\left(4 n+3 n^{2} i\right)\left(2 n^{2}+i\right)}{5 n^{4}} \,.
$$
Show that
$$
\lim_{n \to \infty} z_n = \frac65 i \,.
$$

**Solution.** We find the real and imaginary parts of $z_n$
\begin{align*}
z_n & = \frac{\left(4 n+3 n^{2} i\right)\left(2 n^{2}+i\right)}{5 n^{4}} \\
& = \frac{8 n^{3}+4 n i + 6 n^{4} i + 3 n^{2}i^2}{5 n^{4}} \\
& = \frac{8 n^{3}-3 n^{2}}{5 n^{4}} + \frac{6 n^{4}+4 n}{5 n^{4}} i \\
& = a_n + b_n i \,.
\end{align*}
Using the Algebra of Limits for real sequences we have that
\begin{align*}
& a_n = \frac{8 n^{3}-3 n^{2}}{5 n^{4}}=\frac{ \dfrac{8}{n} - \dfrac{3}{n^2}  }{5} \longrightarrow \frac{0-0}{5}=0 \,, \\
& b_n = \frac{6 n^{4}+4 n}{5 n^{4}}=\frac{6+ \dfrac{4}{n^3} }{5} \longrightarrow \frac{6+0}{5}=\frac{6}{5} \,.
\end{align*}
By Theorem \ref{theorem-convergence-real-imaginary} we conclude
$$
\lim _{n \rightarrow \infty} z_{n} = \lim_{n \to \infty} a_n  +  i \, \lim_{n \to \infty} b_n = 0+\frac{6}{5} i=\frac{6}{5} i \,.
$$


:::

